/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author artur
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null); //centralizar jframe
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt7 = new javax.swing.JButton();
        btAC2 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        BtVirgula = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btDividido = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        btPorcentagem = new javax.swing.JButton();
        btVezes = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btMais = new javax.swing.JButton();
        campo_resultado = new javax.swing.JLabel();
        campo_historico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(269, 423));

        bt7.setBackground(new java.awt.Color(102, 102, 102));
        bt7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 0));
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        btAC2.setBackground(new java.awt.Color(204, 204, 204));
        btAC2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btAC2.setForeground(new java.awt.Color(0, 0, 0));
        btAC2.setText("AC");
        btAC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAC2ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(102, 102, 102));
        bt4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt4.setForeground(new java.awt.Color(0, 0, 0));
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(102, 102, 102));
        bt9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt9.setForeground(new java.awt.Color(0, 0, 0));
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        BtVirgula.setBackground(new java.awt.Color(102, 102, 102));
        BtVirgula.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BtVirgula.setForeground(new java.awt.Color(0, 0, 0));
        BtVirgula.setText(",");
        BtVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVirgulaActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(102, 102, 102));
        bt5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 0, 0));
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(102, 102, 102));
        bt1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 0));
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(102, 102, 102));
        bt2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 0));
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(102, 102, 102));
        bt8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt8.setForeground(new java.awt.Color(0, 0, 0));
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(102, 102, 102));
        bt6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 0, 0));
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        btDividido.setBackground(new java.awt.Color(153, 204, 255));
        btDividido.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btDividido.setForeground(new java.awt.Color(0, 0, 0));
        btDividido.setText("/");
        btDividido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivididoActionPerformed(evt);
            }
        });

        btMenos.setBackground(new java.awt.Color(153, 204, 255));
        btMenos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btMenos.setForeground(new java.awt.Color(0, 0, 0));
        btMenos.setText("-");
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        btIgual.setBackground(new java.awt.Color(102, 204, 255));
        btIgual.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btIgual.setForeground(new java.awt.Color(0, 0, 0));
        btIgual.setText("=");
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });

        btPorcentagem.setBackground(new java.awt.Color(204, 204, 204));
        btPorcentagem.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btPorcentagem.setForeground(new java.awt.Color(0, 0, 0));
        btPorcentagem.setText("%");
        btPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPorcentagemActionPerformed(evt);
            }
        });

        btVezes.setBackground(new java.awt.Color(153, 204, 255));
        btVezes.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btVezes.setForeground(new java.awt.Color(0, 0, 0));
        btVezes.setText("x");
        btVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVezesActionPerformed(evt);
            }
        });

        bt0.setBackground(new java.awt.Color(102, 102, 102));
        bt0.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt0.setForeground(new java.awt.Color(0, 0, 0));
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(102, 102, 102));
        bt3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 0));
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btMais.setBackground(new java.awt.Color(153, 204, 255));
        btMais.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btMais.setForeground(new java.awt.Color(0, 0, 0));
        btMais.setText("+");
        btMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisActionPerformed(evt);
            }
        });

        campo_resultado.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        campo_resultado.setForeground(new java.awt.Color(255, 255, 255));
        campo_resultado.setMaximumSize(new java.awt.Dimension(0, 8));
        campo_resultado.setPreferredSize(new java.awt.Dimension(0, 8));

        campo_historico.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        campo_historico.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btMais, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAC2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDividido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campo_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(campo_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDividido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAC2)
                        .addComponent(btPorcentagem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7)
                    .addComponent(bt8)
                    .addComponent(bt9)
                    .addComponent(btVezes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt5)
                    .addComponent(bt6)
                    .addComponent(btMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(btMais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt0)
                    .addComponent(BtVirgula)
                    .addComponent(btIgual))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String escolha;
    float n1;
    float n2;
    float res;
    
    private void btAC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAC2ActionPerformed
        campo_resultado.setText("");
        campo_historico.setText("");
        
    }//GEN-LAST:event_btAC2ActionPerformed

    private void btPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPorcentagemActionPerformed
        campo_historico.setText(campo_resultado.getText() + " % ");
        n1 = Float.parseFloat(campo_resultado.getText());
        campo_resultado.setText("");
        escolha = "%";
    }//GEN-LAST:event_btPorcentagemActionPerformed

    private void btDivididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivididoActionPerformed
        campo_historico.setText(campo_resultado.getText() + " ÷ ");
        n1 = Float.parseFloat(campo_resultado.getText());
        campo_resultado.setText("");
        escolha = "/";
    }//GEN-LAST:event_btDivididoActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "7");      
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "8"); 
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "9"); 
    }//GEN-LAST:event_bt9ActionPerformed

    private void btVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVezesActionPerformed
        campo_historico.setText(campo_resultado.getText() + " x ");
        n1 = Float.parseFloat(campo_resultado.getText());
        campo_resultado.setText("");
        escolha = "x";
    }//GEN-LAST:event_btVezesActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "4"); 
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "5"); 
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "6");  
    }//GEN-LAST:event_bt6ActionPerformed

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        campo_historico.setText(campo_resultado.getText() + " - ");
        n1 = Float.parseFloat(campo_resultado.getText());
        campo_resultado.setText("");
        escolha = "-";
    }//GEN-LAST:event_btMenosActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "1"); 
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "2"); 
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "3");  
    }//GEN-LAST:event_bt3ActionPerformed

    private void btMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisActionPerformed
        campo_historico.setText(campo_resultado.getText() + " + ");
        n1 = Float.parseFloat(campo_resultado.getText());
        campo_resultado.setText("");
        escolha = "+";
    }//GEN-LAST:event_btMaisActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
       campo_resultado.setText(campo_resultado.getText() + "0"); 
    }//GEN-LAST:event_bt0ActionPerformed

    private void BtVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVirgulaActionPerformed
        campo_resultado.setText(campo_resultado.getText() + ".");
    }//GEN-LAST:event_BtVirgulaActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        campo_historico.setText("");    
        n2 = Float.parseFloat(campo_resultado.getText()); 
        switch (escolha) {
            case "%":
                  campo_resultado.setText(Float.toString(n2 * (n1/100))); 
                break;
            case "+": 
                  campo_resultado.setText(Float.toString(n1+n2));
                break;
            case "-":
                campo_resultado.setText(Float.toString(n1-n2));
                break;
            case "/":
                campo_resultado.setText(Float.toString(n1/n2));
                break;
            case "x":
                campo_resultado.setText(Float.toString(n1*n2));
                break;
        }
         
    }//GEN-LAST:event_btIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtVirgula;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC2;
    private javax.swing.JButton btDividido;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btMais;
    private javax.swing.JButton btMenos;
    private javax.swing.JButton btPorcentagem;
    private javax.swing.JButton btVezes;
    private javax.swing.JLabel campo_historico;
    private javax.swing.JLabel campo_resultado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
